Add oauth2-service
Change-Id: I07351b3d2a0af7f0cd0ee3bba1ad553e4f3cbb3f

diff --git a/packages/uaa/packaging b/packages/uaa/packaging
--- a/packages/uaa/packaging
+++ b/packages/uaa/packaging
@@ -2,7 +2,7 @@
 set -e
 
 cd ${BOSH_INSTALL_TARGET}
-tar zxvf ${BOSH_COMPILE_TARGET}/uaa/jdk1.6.0_35.tar.gz
+tar zxf ${BOSH_COMPILE_TARGET}/uaa/jdk1.6.0_35.tar.gz
 if [[ $? != 0 ]] ; then
   echo "Cannot unpack JDK"
   exit 1
@@ -13,7 +13,7 @@ ln -s jdk/jre
 
 cd ${BOSH_INSTALL_TARGET}
 
-tar zxvf ${BOSH_COMPILE_TARGET}/uaa/apache-tomcat-7.0.32.tar.gz
+tar zxf ${BOSH_COMPILE_TARGET}/uaa/apache-tomcat-7.0.32.tar.gz
 if [[ $? != 0 ]] ; then
   echo "Cannot unpack Tomcat"
   exit 1
@@ -31,3 +31,14 @@ cd ${BOSH_INSTALL_TARGET}
 cp -a ${BOSH_COMPILE_TARGET}/tools/vcap_registrar vcap_registrar
 cd vcap_registrar
 /var/vcap/packages/ruby/bin/bundle --local install --deployment --without=development test
+
+cd ${BOSH_INSTALL_TARGET}
+rm -rf oauth2-service
+tar zxf ${BOSH_COMPILE_TARGET}/uaa/oauth2-service-1.0.0.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Cannot unpack OAuth2 Service"
+  exit 1
+fi
+cd oauth2-service
+/var/vcap/packages/ruby/bin/bundle --local install --deployment --without=development test
+
